<?php if (Mage::helper('cardlink_checkout')->doCheckoutInIframe()) : ?>

    <!-- Modal -->
    <div id="cardlink_checkout--modal">
        <!-- Modal content -->
        <div id="cardlink_checkout--modal-content">
            <iframe id="cardlink_checkout--modal-iframe" src=""></iframe>
        </div>
        <!-- Modal content -->
    </div>
    <!-- Modal -->

    <script>
        const cardlinkCheckoutModal = document.getElementById('cardlink_checkout--modal');

        if (typeof Review.prototype.nextStepLegacy === 'undefined') {
            Review.prototype.nextStepLegacy = Review.prototype.nextStep;

            Review.prototype.nextStep = function(transport) {
                if (transport.responseJSON.success == true) {
                    openCardlinkCheckout(transport.responseJSON.redirect);
                    return;
                }
                Review.prototype.nextStepLegacy(transport);
            }
        }

        function openCardlinkCheckout(url) {
            document.getElementById('cardlink_checkout--modal-iframe').src = url;
            cardlinkCheckoutModal.style.display = "block";
            return false;
        }
    </script>

<?php endif; ?>