<?php

$message = $this->__('Redirecting to Cardlink payment gateway...');
$formData = $this->getFormData();
$paymentGatewayUrl = $this->getPaymentGatewayUrl();

?>
<!doctype html>
<html>

<head>
    <meta charset="utf-8">
    <title><?php echo $message; ?></title>
    <meta name="robots" content="noindex, nofollow" />
    <link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('css/cardlink-checkout.css'); ?>" media="all" />
</head>

<body class="cardlink_checkout--redirect-page">
    <div class="page-title">
        <h1><?php echo $message; ?></h1>
    </div>
    <?php if ($this->getMessage()) : ?>
        <p><?php echo $this->getMessage() ?></p>
    <?php endif; ?>

    <form name="cardlink_checkout" method="post" target="_self" action="<?php echo $paymentGatewayUrl; ?>">
        <?php foreach ($formData as $formFieldKey => $formFieldValue) : ?>
            <input type="hidden" name="<?php echo $formFieldKey; ?>" value="<?php echo $formFieldValue; ?>" />
        <?php endforeach; ?>
    </form>
    <script>
        window.addEventListener('load', function() {
            document.forms["cardlink_checkout"].submit();
        })
    </script>
</body>

</html>